apiVersion: demo.my.domain/v1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: 1-operator-demo
    app.kubernetes.io/managed-by: kustomize
  name: app-sample
spec:
  # TODO(user): Add fields here
