---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-shudong-com-v1-mydeployment
  failurePolicy: Fail
  name: mmydeployment-v1.kb.io
  rules:
  - apiGroups:
    - apps.shudong.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mydeployments
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-shudong-com-v1-mydeployment
  failurePolicy: Fail
  name: vmydeployment-v1.kb.io
  rules:
  - apiGroups:
    - apps.shudong.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mydeployments
  sideEffects: None
