apiVersion: apps.shudong.com/v1
kind: MyDeployment
metadata:
  labels:
    app.kubernetes.io/name: 2-deployment
    app.kubernetes.io/managed-by: kustomize
  name: mydeployment-sample
spec:
  # TODO(user): Add fields here
