apiVersion: apps.shudong.com/v1
kind: MyDeployment
metadata:
  name: mydeployment-nodeport
spec:
  image: my.harbor.cn/k8sstudy/nginx:stable-alpine3.20
  port: 80
  replicas: 2
  expose:
    mode: nodePort
    nodePort: 31080