# permissions for end users to edit mydeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: 2-deployment
    app.kubernetes.io/managed-by: kustomize
  name: mydeployment-editor-role
rules:
- apiGroups:
  - apps.shudong.com
  resources:
  - mydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.shudong.com
  resources:
  - mydeployments/status
  verbs:
  - get
